### PR TITLE
Use a separate include for logging

### LINKED ISSUE #276: 'jq' not installed
Attempted a baremetal deploy using some qct D51B-1u servers. 

I was able to install RHEL 7.6 one these servers after getting the failures attempt to install CentOS on this server fails.

errors from ./01_install_requirements.sh

jq used but not installed -  several failures 1 example
+++ jq -r '.builds[0]'
common.sh: line 42: jq: command not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6067  100  6067    0     0  10056      0 --:--:-- --:--:-- --:--:-- 10044
curl: (23) Failed writing body (0 != 6067)

### PR DESCRIPTION
**Pull request by stbenjam**
Fixes #276

### CODE REVIEW

File: 01_install_requirements.sh [hunk 1]
```diff
@@ -1,8 +1,6 @@
 #!/usr/bin/env bash
 set -ex
 
-source common.sh
```
Comment (hardys) [inline 01_install_requirements.sh]: We probably shouldn't remove this, because it sets up logging - we'll want to retain that, particularly in CI:

https://github.com/openshift-metalkube/dev-scripts/blob/master/common.sh#L121..L129

Perhaps we can move that to a common_logging.sh or similar as I mentioned in https://github.com/openshift-metalkube/dev-scripts/pull/281 ?

Comment (stbenjam) [reply 01_install_requirements.sh]: Yea I think that's reasonable - updated

**Comment by derekhiggins** [comment]
Build FAILURE, see build http://10.8.144.11:8080/job/dev-tools/507/

**Comment by hardys** [comment]
Ok the CI failure (now we have logs, yay!) was probably because some pods got OOMKilled:

```
[shardy@localhost logs]$ cat failing_pods.log 
NAMESPACE                                               NAME                                                              READY   STATUS              RESTARTS   AGE
openshift-authentication                                openshift-authentication-787cf7cff-t7fhl                          1/1     Terminating         0          20m
openshift-console                                       console-6d7fd96567-8jq45                                          0/1     Terminating         0          22m
openshift-ingress                                       router-default-9b75b8c9c-qv68g                                    0/1     Pending             0          9m7s
openshift-ingress                                       router-default-9b75b8c9c-zx5p9                                    1/1     Terminating         0          20m
openshift-kube-apiserver                                kube-apiserver-master-2                                           0/2     Pending             0          20m
openshift-kube-apiserver                                revision-pruner-1-master-1                                        0/1     OOMKilled           0          39m
openshift-kube-apiserver                                revision-pruner-3-master-1                                        0/1     OOMKilled           0          20m
openshift-kube-controller-manager                       installer-5-master-2                                              0/1     OOMKilled           0          35m
```

We're discussing increasing the memory and CPU in https://github.com/openshift-metalkube/dev-scripts/pull/254 so maybe we should just merge that to improve the CI pass rate (weird that it doesn't always happen though?)
